laravel/routes/web.php
<?php


Route::resource('shares', 'ShareController');
Route::get('/', 'ShareController@index')->name('dashboard');
Route::get('/home', 'ShareController@home')->name('home');
Route::get('/shares/create', 'ShareController@create');
Route::get('/shares/datakendaraan/idkendaraan={idkendaraan}', 'DataKendaraanController@getData');
Route::get('/blank', 'DataKendaraanController@blankView');

Route::get('/detail/idkendaraan={idkendaraan}', 'DataKendaraanController@detailkendaraan')->name('detaildata');;
Route::get('/datakendaraan/list/{idkendaraan}', 'DataKendaraanController@getDataJson');
Route::get('/detail', 'DataKendaraanController@printPDF')->name('printPDF');

Route::get('/login', 'UserController@login');
Route::post('/loginPost', 'UserController@loginPost');
Route::get('/logout', 'UserController@logout');
Route::get('/register', 'UserController@register');
Route::post('/registerPost', 'UserController@registerPost');


// Auth::routes();
// Route::get('/home', 'HomeController@index')->name('home');

laravel/app/Share.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Share extends Model
{
    protected $fillable = [
        'share_name',
        'share_price',
        'share_qty'
      ];
}

laravel/app/Http/Controllers/ShareController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Validator;
use App\Share;
use App\Datakendaraan;
use App\Dimensi;
use App\Karoseri;
use File;
use DB;
use Datatables;
use Log;
use Qr;

class ShareController extends Controller
{

    /**
     * Validate the user insert request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    protected function validateInsert(Request $request)
    {
        $request->validate([

            'no_srut'=> 'required|min:5',
            'no_skrb'=> 'required|min:5',
            'tgl_skrb'=> 'required|string',
            'no_rangka'=> 'required|string',
            'no_mesin'=> 'required|string',
            'merek'=> 'required|string',
            'jenis_kendaraan'=> 'required|string',
            'warna_kendaraan'=> 'required|string',
            'lampiran'=> 'required|string',
            'jmlh_silinder'=> 'required|string',
            'isi_silinder'=> 'required|string',
            'pjg_boxbak'=> 'required|string',
            'tnggi_boxbaktang'=> 'required|string',
            'jmlh_tmpt_ddk'=> 'required|string',
            'daya_mtr'=> 'required|string',
            'lbr_boxbaktang'=> 'required|string',
            'rmh_bdn'=> 'required|string',
            'jbb'=> 'required|string',
            'jbkb'=> 'required|string',
            'jns_angkutan'=> 'required|string',
            'jbi'=> 'required|string',
            'jbki'=> 'required|string',
            'bhan_bkr'=> 'required|string',
            'sudut_pgi'=> 'required|string',
            'pntu_darurat'=> 'required|string',
            'varian'=> 'required|string',
            'kt_baktang'=> 'required|string',
            'panjang_ttl'=> 'required|string',
            'lebar_ttl'=> 'required|string',
            'tinggi_ttl'=> 'required|string',
            'jarak_smb12'=> 'required|string',
            'rear_overhang'=> 'required|string',
            'jarak_smb23'=>  'required|string',
            'front_overhang'=> 'required|string',
            'jarak_smb34'=>  'required|string',
            'img_tmpk_depan'=> 'image|mimes:jpg,png,jpeg|max:5000',//4mb
            'img_tmpk_smpng'=> 'image|mimes:jpg,png,jpeg|max:5000',//4mb
            'img_tmpk_blkng'=> 'image|mimes:jpg,png,jpeg|max:5000',//4mb
            'ukrn_smb1' => 'required|string',
            'ukrn_smb2' => 'required|string',
            'ukrn_smb3' => 'required|string',
            'ukrn_smb4' => 'required|string',
            'kekuatan_rancangan_smb1' => 'required|string',
            'kekuatan_rancangan_smb2' => 'required|string',
            'kekuatan_rancangan_smb3' => 'required|string',
            'kekuatan_rancangan_smb4' => 'required|string',
            'tnggi_box_bak_tang' => 'required|string',
            'rmh_bdn_2' => 'required|string',
            'knfg_smb' => 'required|string',
            'kls_jln' => 'required|string',
            'lbr_pntu_spr' => 'required|string',
            'jrk_bngku' => 'required|string',
            'brt_ksng' => 'required|string',
            'dya_angkt_brng' => 'required|string',
            'dya_angkt_pnmpng' => 'required|string',
            'kssuaian_lndsn' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_bntk_fsk' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_dmnsi_kndraan' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_material' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_pss_lmpu' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_ukrn' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_dmnsi_muatan' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_vlm_muatan' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_dmnsi_ddk' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_jrk_ddk' => 'required|in:Sesuai,Tidak Sesuai',
            'kssuaian_keluar_drrt' =>'required|in:Sesuai,Tidak Sesuai'
        ],[
            'no_srut.required' => ' Nomor Srut harus diisi.',
            'no_srut.min' => ' Nomor Srut minimal 5 karakter.',
            'no_srut.max' => ' Nomor Srut maksimal 35 karakter',
            'no_skrb.required' => ' Nomor SK Rancang Bangun harus diisi.',
            'no_skrb.min' => ' Nomor SK Rancang Bangun minimal 5 karakter.',
            'no_skrb.max' => ' Nomor SK Rancang Bangun tidak melebihi 35 karakter.',
            'numeric' => ' Isi inputan harus berupa angka',
            'tgl_skrb.required'=> 'Tanggal SK Rancang Bangun harus diisi.',
            'no_rangka.required'=> ' Nomor Rangka harus diisi.',
            'no_mesin.required'=> 'Nomor Mesinharus diisi.',
            'merek.required'=> 'Merek harus diisi.',
            'jenis_kendaraan.required'=> 'Jenis kendaraan harus diisi.',
            'warna_kendaraan.required'=> 'Warna kendaraan harus diisi.',
            'lampiran.required'=> 'Lampiran harus diisi.',
            'jmlh_silinder.required'=> 'Jumlah silinder harus diisi.',
            'isi_silinder.required'=> 'Isi silinder harus diisi.',
            'pjg_boxbak.required'=> 'Panjang Box/Bak harus diisi.',
            'tnggi_boxbaktang.required'=> 'Tinggi Box/Bak harus diisi.',
            'jmlh_tmpt_ddk.required'=> 'Jumlah tempat dudukharus diisi.',
            'daya_mtr.required'=> 'Daya Motor harus diisi.',
            'lbr_boxbaktang.required'=> 'Lebar Box/Bak/Tang harus diisi.',
            'rmh_bdn.required'=> 'Rumah Badan harus diisi.',
            'jbb.required'=> 'JBB harus diisi.',
            'jbkb.required'=> 'JBKB harus diisi.',
            'jns_angkutan.required'=> 'Jenis angkutan harus diisi.',
            'jbi.required'=> 'JBI harus diisi.',
            'jbki.required'=> 'JBKI harus diisi.',
            'bhan_bkr.required'=> 'Bahan Bakar harus diisi.',
            'sudut_pgi.required'=> 'Sudut perigi harus diisi.',
            'pntu_darurat.required'=> 'Pintu darurat harus diisi.',
            'varian.required'=> 'Varian harus diisi.',
            'kt_baktang'=> 'Keterangan Bak/Tang harus diisi.',
            'panjang_ttl.required'=> 'Panjang total harus diisi.',
            'lebar_ttl.required'=> 'Lebar total harus diisi.',
            'tinggi_ttl.required'=> 'Tinggi total harus diisi.',
            'jarak_smb12.required'=> 'Jarak sumbu 1-2 harus diisi.',
            'rear_overhang.required'=> 'Rear overhang harus diisi.',
            'jarak_smb23.required'=>  'Jarak sumbu 2-3 harus diisi.',
            'front_overhang.required'=> 'Front overhang harus diisi.',
            'jarak_smb34.required'=>  'Jarak sumbu 3-4 harus diisi.',
            'img_tmpk_depan.required'=> 'Gambar tampak depan harus diisi.',//4mb
            'img_tmpk_smpng.required'=> 'Gambar tampak samping harus diisi.',
            'img_tmpk_blkng.required'=> 'Gambar tampak  belakang harus diisi.',
            'ukrn_smb1.required' => 'Ukuran sumbu 1 harus diisi.',
            'ukrn_smb2.required' => 'ukuran sumbu 2 harus diisi.',
            'ukrn_smb3.required' => 'Ukuran sumbu 3 harus diisi.',
            'ukrn_smb4.required' => 'Ukuran sumbu 4 harus diisi.',
            'kekuatan_rancangan_smb1' => 'Kekuatan ban pada sumbu 1',
            'kekuatan_rancangan_smb2' => 'Kekuatan ban pada sumbu 2',
            'kekuatan_rancangan_smb3' => 'Kekuatan ban pada sumbu 3',
            'kekuatan_rancangan_smb4' => 'Kekuatan ban pada sumbu 4',
            'tnggi_box_bak_tang.required' => 'Tinggi box/bak/tang harus diisi.',
            'rmh_bdn_2.required' => 'harus diisi.',
            'knfg_smb.required' => 'Konfigurasi sumbu harus diisi.',
            'kls_jln.required' => 'Kelas jalan harus diisi.',
            'lbr_pntu_spr.required' => 'Lebar pintu supir harus diisi.',
            'jrk_bngku.required' => 'Jarak bangku harus diisi.',
            'brt_ksng.required' => 'Berat kosong harus diisi.',
            'dya_angkt_brng.required' => 'Daya angkut barang harus diisi.',
            'dya_angkt_pnmpng.required' => 'Daya angkut penumpang harus diisi.',
            'kssuaian_lndsn.required' => 'Kesesuaian landasan harus diisi.',
            'kssuaian_bntk_fsk.required' => 'Kesesuaian bentuk fisik harus diisi.',
            'kssuaian_dmnsi_kndraan.required' => 'Kesesuaian dimensi kendaraan harus diisi.',
            'kssuaian_material.required' => 'Kesesuaian material harus diisi.',
            'kssuaian_pss_lmpu.required' => 'Kesesuaian posisi lampu harus diisi.',
            'kssuaian_ukrn.required' => 'Kesesuaian ukuran harus diisi.',
            'kssuaian_dmnsi_muatan' => 'Kesesuaian dimensi muatan harus diisi.',
            'kssuaian_vlm_muatan.required' => 'Kesesuaian volume muatan harus diisi.',
            'kssuaian_dmnsi_ddk.required' => 'Kesesuaian dimensi duduk harus diisi.',
            'kssuaian_jrk_ddk.required' => 'Kesesuaian jarak tempat duduk harus diisi.',
            'kssuaian_keluar_drrt.required' =>'Kesesuaian fasilitas tempat keluar darurat harus diisi.'

        ]);

    }

    public function index()
    {

        return view('blank');

    }

    public function home(){
        if(!Session::get('login')){
            return redirect('login')->with('alert','Kamu harus login dulu');
        }
        else{


        $datakendaraan = DB::table('datakendaraans')
        ->join('dimensis', 'datakendaraans.idkendaraan', '=', 'dimensis.idkendaraan')
        ->join('karoseris', 'karoseris.idkendaraan', '=', 'dimensis.idkendaraan')
        ->select('*')
        ->get();
        // $datakendaraan = Datakendaraan::all();

        return view('shares.index', compact('datakendaraan'));
        }
    }
    public function create()
    {
        if(!Session::get('login')){
            return redirect('login')->with('alert','Kamu harus login dulu');
        }
        else{

        return view('shares.create');
        }
    }

laravel/resources/views/shares/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />


	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{{ asset('assets/css/animate.min.css') }}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{{ asset('assets/css/light-bootstrap-dashboard.css?v=1.4.0') }}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{{ asset('assets/css/demo.css') }}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{{ asset('assets/css/pe-icon-7-stroke.css') }}" rel="stylesheet" />


    <!--   Core JS Files   -->
    <script src="{{ asset('assets/js/jquery.3.2.1.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>
    <script src="{{ asset('assets/js/bootstrap.min.js') }}" type="text/javascript"></script>
    <style type="text/css">
      .box{
        width:600px;
        margin:0 auto;
        border:1px solid #ccc;
        display: flex;
        justify-content: center;
      }
      .vertical-center {
        min-height: 100%;  /* Fallback for browsers do NOT support vh unit */
        min-height: 100vh; /* These two lines are counted as one :-)       */

        display: flex;
        align-items: center;
      }
      body {
        background-image: url("image/logo_login.jpg");
        background-color: #cccccc;
      }
    </style>
</head>
<body>
        
        @yield('content')
      </div>
  </div>
</div> 
      </div>   
        <!--  Notifications Plugin    -->
        <script src="{{ asset('assets/js/bootstrap-notify.js') }}"></script>

        <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
        <script src="{{ asset('assets/js/light-bootstrap-dashboard.js?v=1.4.0') }}"></script>

        <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
        <script src="{{ asset('assets/js/demo.js') }}"></script>
</body>
</html>

laravel/resources/views/shares/index.blade.php
@extends('dashboard')

@section('content')
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.material.min.css" />
<div class="card ">
  <div class="header">
      <h4 class="title">Data Srut</h4>
      <p class="category">List Semua Kendaraan</p>
  </div>
  <div class="content" style="overflow-x:auto;">
      <!-- table Data kendaraan -->
    <table id = "datakendaraan" class="table table-striped">
      <thead>
          <tr>
            <td>Nomor</td>
            <td>Id</td>
            <td>No.Srut</td>
            <td>No.SK Rancang Bangun</td>
            <td>Tanggal SK Rancang Bangun</td>
            <td>Nomor Rangka</td>
            <td>Action</td>
            <td></td>
          </tr>
      </thead>
      <tbody>
        <?php $no = 1;?>
          @foreach($datakendaraan as $datakendaraan)
          <tr>
              <td>{{$no++}}
              <td>{{$datakendaraan->idkendaraan}}</td>
              <td>{{$datakendaraan->no_srut}}</td>
              <td>{{$datakendaraan->no_skrb}}</td>
              <td>{{$datakendaraan->tgl_skrb}}</td>
              <td><img src="{{URL::asset('images/'.$datakendaraan->qrCode)}}" id="tabel"/></td>
              <td>
                  
                  <a class="btn btn-info" href="{{ route('detaildata',$datakendaraan->idkendaraan)}}">Detail</a>
              </td>
              <td>
                  <a href="{{ route('shares.edit',$datakendaraan->idkendaraan)}}" class="btn btn-primary">Edit</a>
              </td>
              <td>
                  <form action="{{ route('shares.destroy', $datakendaraan->idkendaraan)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">Delete</button>
                  </form>
                  <!-- <a href="{{ route('printPDF',$datakendaraan->idkendaraan)}}" class="btn btn-primary">CETAK PDF</a> -->
              </td>
          </tr>
          @endforeach
      </tbody>
    </table>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    var table = $('#datakendaraan').DataTable({
      "bInfo": false,
      "bLengthChange": false
    });
} );
</script>
@endsection
@section('modal')
<script type="text/javascript">
    $('#datakendaraan').on('click', 'tr', function () {
        var name = $('td', this).eq(0).text();
        console.log(name);
        var url = "{{ url('datakendaraan/list/') }}/"+name;
        var fileloc = "{{URL::asset('images/')}}";
        $.get( url, function( data ) {
          console.log(data);
          $('.modal-body').empty();
          $('<div id="dialog_content"><h4>Data Kendaraan</h4></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>ID KENDARAAN     : '+data[0].idkendaraan+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>NO SRUT          : '+data[0].no_srut+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>NO SKRB          : '+data[0].no_skrb+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>TANGGAL SKRB     : '+data[0].tgl_skrb+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>NO RANGKA        : '+data[0].no_rangka+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>NO MESIN         : '+data[0].no_mesin+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>MEREK            : '+data[0].merek+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>JENIS_KENDARAAN  : '+data[0].jenis_kendaraan+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>WARNA KENDARAAN  : '+data[0].warna_kendaraan+'</li></div>').appendTo("#bodymodal");

          $('<div id="dialog_content"><hr>').appendTo('#bodymodal');          
          
          $('<div id="dialog_content"><h4>Bentuk Fisik Kendaraan</h4></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>ID KENDARAAN     : <img src="'+fileloc+'/'+data[0].qrCode+'"/></li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>NO SRUT          : '+data[0].no_srut+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>NO SKRB          : '+data[0].no_skrb+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>TANGGAL SKRB     : '+data[0].tgl_skrb+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>NO RANGKA        : '+data[0].no_rangka+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>NO MESIN         : '+data[0].no_mesin+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>MEREK            : '+data[0].merek+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>JENIS_KENDARAAN  : '+data[0].jenis_kendaraan+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><li>WARNA KENDARAAN  : '+data[0].warna_kendaraan+'</li></div>').appendTo("#bodymodal");
          $('<div id="dialog_content"><hr>').appendTo('#bodymodal');          
          $('#DescModal').modal("show");
        });
    });
    
</script>
@endsection

laravel/resources/views/shares/login.blade.php
@extends('shares.dashboard')
@section('content')
<div class="vertical-center">
    <div class="container box">
        <!-- Main Section -->
        <section class="main-section">
            <!-- Add Your Content Inside -->
            <div class="content">
                <!-- Remove This Before You Start -->
                <h1 style="color:white;">Admin -  Login</h1>
                <hr>
                @if(\Session::has('alert'))
                    <div class="alert alert-danger">
                        <div>{{Session::get('alert')}}</div>
                    </div>
                @endif
                @if(\Session::has('alert-success'))
                    <div class="alert alert-success">
                        <div>{{Session::get('alert-success')}}</div>
                    </div>
                @endif
                <form action="{{ url('/loginPost') }}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="username" style="color:white;">Username:</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <div class="form-group">
                        <label for="alamat" style="color:white;">Password:</label>
                        <input type="password" class="form-control" id="password" name="password"/>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">Login</button>
                    </div>
                </form>
            </div>
            <!-- /.content -->
        </section>
        <!-- /.main-section -->
    </div>
</div>    
@endsection

laravel/resources/views/shares/register.blade.php
@extends('dashboard')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            <h1>Register User</h1>
            <hr>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ url('/registerPost') }}" method="post">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="username">Username:</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <div class="form-group">
                    <label for="alamat">Password:</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <div class="form-group">
                    <label for="alamat">Password Confirmation:</label>
                    <input type="password" class="form-control" id="confirmation" name="confirmation">
                </div>
                <div class="form-group">
                    <label for="alamat">Name:</label>
                    <input type="text"  class="form-control" id="name" name="name">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Submit</button>
                    <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                </div>
            </form>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

laravel/resources/views/shares/temp.blade.php
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif

  <!-- table Data kendaraan -->
  <table class="table table-striped">
    <thead>
        <tr>
          <td>No.Srut</td>
          <td>No.SK Rancang Bangun</td>
          <td>Tanggal SK Rancang Bangun</td>
          <td>Nomor Rangka</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($datakendaraan as $datakendaraan)
        <tr>
            <td>{{$datakendaraan->no_srut}}</td>
            <td>{{$datakendaraan->no_skrb}}</td>
            <td>{{$datakendaraan->tgl_skrb}}</td>
            <td><img src="{{URL::asset('/images/'.$datakendaraan->qrCode)}}"/></td>
            <td><a href="{{ route('shares.edit',$datakendaraan->idkendaraan)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('shares.destroy', $datakendaraan->idkendaraan)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>